### PR TITLE
Content from Flatpaked Steam and Shadow Warrior Support

### PR DESCRIPTION
**Pull request by ColinKinloch**
Give the EDuke32 flatpak access to flatpaked Steam and update the search path patch to check flatpaked steam directories.
Compile VoidSW to support the Build Engine game Shadow Warrior.

### CODE REVIEW

**Comment by ColinKinloch** [comment]
@FakeShemp 
Should VoidSW be a separate package?
They share a repo, dependencies and a buildsystem but beyond that they seem to be separate codebases.
However I feel a separate VoidSW package would just increase maintenance complexity.

**Comment by FakeShemp** [comment]
I'm not sure as I have never built it or used it myself.

What do others think about several (related) build targets in one manifest like this? 

@bilelmoussaoui 
@hfiguiere

**Comment by hfiguiere** [comment]
I have stricty no idea.

**Comment by FakeShemp** [comment]
Just tested this and it just works. Very nice work.

I think I'll just merge this and if people have problems with all the build engines in one package, we can discuss it then.

**Pull request merged**
