### PR TITLE
Update platform to 23.08 and use ffmpeg to generate icons from source

### PR DESCRIPTION
**Pull request by ColinKinloch**
The EDuke32 tarball contains icons in psd format. `org.freedesktop.Platform//23.08beta` has ffmpeg with support for decoding Photoshop psd files.

This means we can generate icons at build once 23.08 is stable.

### CODE REVIEW

**Comment by Hendricks266** [comment]
You may want to use the 32x32 (really anything 48x48 and smaller) from our .ico instead of generating one from the .psd, because those have been custom tweaked for small resolutions.

**Comment by ColinKinloch** [comment]
Oh, neat.
Unfortunately I'm not sure the freedesktop sdk has anything to dump the contents .ico files. At first glance `ffmpeg` in version `23.08beta` only seems to dump it at 256px.
There are different flatpaks that compile ImageMagick as part of the build but using ffmpeg was my attempt at avoiding that waste.

**Comment by ColinKinloch** [comment]
Also what is the preferred icon for Mapster32?
Currently the orange icon is being used.

**Comment by ColinKinloch** [comment]
I figured it out, ffmpeg exposes the different resolutions as different streams so `-map 0:10` is 256px png.
I've also set it up to rotate the hue of the .ico for the level editor logos.

**Pull request merged**
